# Generated by Django 4.2.15 on 2024-08-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0002_poem_image_poem_type_alter_poem_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
